# Source list, include dirs and optional-extension wiring for PHP 8.3.33.
# Included by the generic components/php/CMakeLists.txt, which sets
# PHP_SRC (fetched tree), PHP_VER_DIR (this dir) and PHP_COMPONENT_DIR.

set(PHP_SRCS
    ${PHP_SRC}/ext/hash/hash_adler32.c
    ${PHP_SRC}/ext/hash/hash_crc32.c
    ${PHP_SRC}/ext/hash/hash_fnv.c
    ${PHP_SRC}/ext/hash/hash_gost.c
    ${PHP_SRC}/ext/hash/hash_haval.c
    ${PHP_SRC}/ext/hash/hash_joaat.c
    ${PHP_SRC}/ext/hash/hash_md.c
    ${PHP_SRC}/ext/hash/hash_murmur.c
    ${PHP_SRC}/ext/hash/hash.c
    ${PHP_SRC}/ext/hash/hash_ripemd.c
    ${PHP_SRC}/ext/hash/hash_sha3.c
    ${PHP_SRC}/ext/hash/hash_sha.c
    ${PHP_SRC}/ext/hash/hash_snefru.c
    ${PHP_SRC}/ext/hash/hash_tiger.c
    ${PHP_SRC}/ext/hash/hash_whirlpool.c
    ${PHP_SRC}/ext/hash/hash_xxhash.c
    ${PHP_SRC}/ext/hash/murmur/PMurHash128.c
    ${PHP_SRC}/ext/hash/murmur/PMurHash.c
    ${PHP_SRC}/ext/hash/sha3/generic64lc/KeccakHash.c
    ${PHP_SRC}/ext/hash/sha3/generic64lc/KeccakP-1600-opt64.c
    ${PHP_SRC}/ext/hash/sha3/generic64lc/KeccakSponge.c
    ${PHP_SRC}/ext/json/json_encoder.c
    ${PHP_SRC}/ext/json/json.c
    ${PHP_SRC}/ext/json/json_parser.tab.c
    ${PHP_SRC}/ext/json/json_scanner.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_auto_possess.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_chartables.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_compile.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_config.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_context.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_convert.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_dfa_match.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_error.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_extuni.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_find_bracket.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_jit_compile.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_maketables.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_match_data.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_match.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_newline.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_ord2utf.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_pattern_info.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_script_run.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_serialize.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_string_utils.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_study.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_substitute.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_substring.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_tables.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_ucd.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_valid_utf.c
    ${PHP_SRC}/ext/pcre/pcre2lib/pcre2_xclass.c
    ${PHP_SRC}/ext/pcre/php_pcre.c
    ${PHP_SRC}/ext/random/csprng.c
    ${PHP_SRC}/ext/random/engine_combinedlcg.c
    ${PHP_SRC}/ext/random/engine_mt19937.c
    ${PHP_SRC}/ext/random/engine_pcgoneseq128xslrr64.c
    ${PHP_SRC}/ext/random/engine_secure.c
    ${PHP_SRC}/ext/random/engine_user.c
    ${PHP_SRC}/ext/random/engine_xoshiro256starstar.c
    ${PHP_SRC}/ext/random/gammasection.c
    ${PHP_SRC}/ext/random/randomizer.c
    ${PHP_SRC}/ext/random/random.c
    ${PHP_SRC}/ext/reflection/php_reflection.c
    ${PHP_SRC}/ext/spl/php_spl.c
    ${PHP_SRC}/ext/spl/spl_array.c
    ${PHP_SRC}/ext/spl/spl_directory.c
    ${PHP_SRC}/ext/spl/spl_dllist.c
    ${PHP_SRC}/ext/spl/spl_exceptions.c
    ${PHP_SRC}/ext/spl/spl_fixedarray.c
    ${PHP_SRC}/ext/spl/spl_functions.c
    ${PHP_SRC}/ext/spl/spl_heap.c
    ${PHP_SRC}/ext/spl/spl_iterators.c
    ${PHP_SRC}/ext/spl/spl_observer.c
    ${PHP_SRC}/ext/standard/array.c
    ${PHP_SRC}/ext/standard/assert.c
    ${PHP_SRC}/ext/standard/base64.c
    ${PHP_SRC}/ext/standard/basic_functions.c
    ${PHP_SRC}/ext/standard/browscap.c
    ${PHP_SRC}/ext/standard/crc32.c
    ${PHP_SRC}/ext/standard/crc32_x86.c
    ${PHP_SRC}/ext/standard/credits.c
    ${PHP_SRC}/ext/standard/crypt_blowfish.c
    ${PHP_SRC}/ext/standard/crypt_freesec.c
    ${PHP_SRC}/ext/standard/crypt.c
    ${PHP_SRC}/ext/standard/crypt_sha256.c
    ${PHP_SRC}/ext/standard/crypt_sha512.c
    ${PHP_SRC}/ext/standard/css.c
    ${PHP_SRC}/ext/standard/datetime.c
    ${PHP_SRC}/ext/standard/dir.c
    ${PHP_SRC}/ext/standard/dl.c
    ${PHP_SRC}/ext/standard/dns.c
    ${PHP_SRC}/ext/standard/exec.c
    ${PHP_SRC}/ext/standard/file.c
    ${PHP_SRC}/ext/standard/filestat.c
    ${PHP_SRC}/ext/standard/filters.c
    ${PHP_SRC}/ext/standard/flock_compat.c
    ${PHP_SRC}/ext/standard/formatted_print.c
    ${PHP_SRC}/ext/standard/fsock.c
    ${PHP_SRC}/ext/standard/ftok.c
    ${PHP_SRC}/ext/standard/ftp_fopen_wrapper.c
    ${PHP_SRC}/ext/standard/head.c
    ${PHP_SRC}/ext/standard/hrtime.c
    ${PHP_SRC}/ext/standard/html.c
    ${PHP_SRC}/ext/standard/http_fopen_wrapper.c
    ${PHP_SRC}/ext/standard/http.c
    ${PHP_SRC}/ext/standard/image.c
    ${PHP_SRC}/ext/standard/incomplete_class.c
    ${PHP_SRC}/ext/standard/info.c
    ${PHP_SRC}/ext/standard/iptc.c
    ${PHP_SRC}/ext/standard/levenshtein.c
    ${PHP_SRC}/ext/standard/libavifinfo/avifinfo.c
    ${PHP_SRC}/ext/standard/link.c
    ${PHP_SRC}/ext/standard/mail.c
    ${PHP_SRC}/ext/standard/math.c
    ${PHP_SRC}/ext/standard/md5.c
    ${PHP_SRC}/ext/standard/metaphone.c
    ${PHP_SRC}/ext/standard/microtime.c
    ${PHP_SRC}/ext/standard/net.c
    ${PHP_SRC}/ext/standard/pack.c
    ${PHP_SRC}/ext/standard/pageinfo.c
    ${PHP_SRC}/ext/standard/password.c
    ${PHP_SRC}/ext/standard/php_crypt_r.c
    ${PHP_SRC}/ext/standard/php_fopen_wrapper.c
    ${PHP_SRC}/ext/standard/proc_open.c
    ${PHP_SRC}/ext/standard/quot_print.c
    ${PHP_SRC}/ext/standard/scanf.c
    ${PHP_SRC}/ext/standard/sha1.c
    ${PHP_SRC}/ext/standard/soundex.c
    ${PHP_SRC}/ext/standard/streamsfuncs.c
    ${PHP_SRC}/ext/standard/string.c
    ${PHP_SRC}/ext/standard/strnatcmp.c
    ${PHP_SRC}/ext/standard/syslog.c
    ${PHP_SRC}/ext/standard/type.c
    ${PHP_SRC}/ext/standard/uniqid.c
    ${PHP_SRC}/ext/standard/url.c
    ${PHP_SRC}/ext/standard/url_scanner_ex.c
    ${PHP_SRC}/ext/standard/user_filters.c
    ${PHP_SRC}/ext/standard/uuencode.c
    ${PHP_SRC}/ext/standard/var.c
    ${PHP_SRC}/ext/standard/var_unserializer.c
    ${PHP_SRC}/ext/standard/versioning.c
    ${PHP_SRC}/main/explicit_bzero.c
    ${PHP_SRC}/main/fopen_wrappers.c
    ${PHP_SRC}/main/getopt.c
    ${PHP_SRC}/main/main.c
    ${PHP_SRC}/main/network.c
    ${PHP_SRC}/main/output.c
    ${PHP_SRC}/main/php_content_types.c
    ${PHP_SRC}/main/php_ini_builder.c
    ${PHP_SRC}/main/php_ini.c
    ${PHP_SRC}/main/php_odbc_utils.c
    ${PHP_SRC}/main/php_open_temporary_file.c
    ${PHP_SRC}/main/php_scandir.c
    ${PHP_SRC}/main/php_syslog.c
    ${PHP_SRC}/main/php_ticks.c
    ${PHP_SRC}/main/php_variables.c
    ${PHP_SRC}/main/reentrancy.c
    ${PHP_SRC}/main/rfc1867.c
    ${PHP_SRC}/main/safe_bcmp.c
    ${PHP_SRC}/main/SAPI.c
    ${PHP_SRC}/main/snprintf.c
    ${PHP_SRC}/main/spprintf.c
    ${PHP_SRC}/main/streams/cast.c
    ${PHP_SRC}/main/streams/filter.c
    ${PHP_SRC}/main/streams/glob_wrapper.c
    ${PHP_SRC}/main/streams/memory.c
    ${PHP_SRC}/main/streams/mmap.c
    ${PHP_SRC}/main/streams/plain_wrapper.c
    ${PHP_SRC}/main/streams/streams.c
    ${PHP_SRC}/main/streams/transports.c
    ${PHP_SRC}/main/streams/userspace.c
    ${PHP_SRC}/main/streams/xp_socket.c
    ${PHP_SRC}/main/strlcat.c
    ${PHP_SRC}/main/strlcpy.c
    ${PHP_SRC}/sapi/embed/php_embed.c
    ${PHP_SRC}/TSRM/TSRM.c
    ${PHP_SRC}/Zend/Optimizer/block_pass.c
    ${PHP_SRC}/Zend/Optimizer/compact_literals.c
    ${PHP_SRC}/Zend/Optimizer/compact_vars.c
    ${PHP_SRC}/Zend/Optimizer/dce.c
    ${PHP_SRC}/Zend/Optimizer/dfa_pass.c
    ${PHP_SRC}/Zend/Optimizer/escape_analysis.c
    ${PHP_SRC}/Zend/Optimizer/nop_removal.c
    ${PHP_SRC}/Zend/Optimizer/optimize_func_calls.c
    ${PHP_SRC}/Zend/Optimizer/optimize_temp_vars_5.c
    ${PHP_SRC}/Zend/Optimizer/pass1.c
    ${PHP_SRC}/Zend/Optimizer/pass3.c
    ${PHP_SRC}/Zend/Optimizer/sccp.c
    ${PHP_SRC}/Zend/Optimizer/scdf.c
    ${PHP_SRC}/Zend/Optimizer/zend_call_graph.c
    ${PHP_SRC}/Zend/Optimizer/zend_cfg.c
    ${PHP_SRC}/Zend/Optimizer/zend_dfg.c
    ${PHP_SRC}/Zend/Optimizer/zend_dump.c
    ${PHP_SRC}/Zend/Optimizer/zend_func_info.c
    ${PHP_SRC}/Zend/Optimizer/zend_inference.c
    ${PHP_SRC}/Zend/Optimizer/zend_optimizer.c
    ${PHP_SRC}/Zend/Optimizer/zend_ssa.c
    ${PHP_SRC}/Zend/zend_alloc.c
    ${PHP_SRC}/Zend/zend_API.c
    ${PHP_SRC}/Zend/zend_ast.c
    ${PHP_SRC}/Zend/zend_atomic.c
    ${PHP_SRC}/Zend/zend_attributes.c
    ${PHP_SRC}/Zend/zend_builtin_functions.c
    ${PHP_SRC}/Zend/zend_call_stack.c
    ${PHP_SRC}/Zend/zend_closures.c
    ${PHP_SRC}/Zend/zend_compile.c
    ${PHP_SRC}/Zend/zend_constants.c
    ${PHP_SRC}/Zend/zend_cpuinfo.c
    ${PHP_SRC}/Zend/zend_default_classes.c
    ${PHP_SRC}/Zend/zend_dtrace.c
    ${PHP_SRC}/Zend/zend_enum.c
    ${PHP_SRC}/Zend/zend_exceptions.c
    ${PHP_SRC}/Zend/zend_execute_API.c
    ${PHP_SRC}/Zend/zend_execute.c
    ${PHP_SRC}/Zend/zend_extensions.c
    ${PHP_SRC}/Zend/zend_fibers.c
    ${PHP_SRC}/Zend/zend_float.c
    ${PHP_SRC}/Zend/zend_gc.c
    ${PHP_SRC}/Zend/zend_gdb.c
    ${PHP_SRC}/Zend/zend_generators.c
    ${PHP_SRC}/Zend/zend_hash.c
    ${PHP_SRC}/Zend/zend_highlight.c
    ${PHP_SRC}/Zend/zend_hrtime.c
    ${PHP_SRC}/Zend/zend_inheritance.c
    ${PHP_SRC}/Zend/zend_ini.c
    ${PHP_SRC}/Zend/zend_ini_parser.c
    ${PHP_SRC}/Zend/zend_ini_scanner.c
    ${PHP_SRC}/Zend/zend_interfaces.c
    ${PHP_SRC}/Zend/zend_iterators.c
    ${PHP_SRC}/Zend/zend_language_parser.c
    ${PHP_SRC}/Zend/zend_language_scanner.c
    ${PHP_SRC}/Zend/zend_list.c
    ${PHP_SRC}/Zend/zend_llist.c
    ${PHP_SRC}/Zend/zend_max_execution_timer.c
    ${PHP_SRC}/Zend/zend_multibyte.c
    ${PHP_SRC}/Zend/zend.c
    ${PHP_SRC}/Zend/zend_object_handlers.c
    ${PHP_SRC}/Zend/zend_objects_API.c
    ${PHP_SRC}/Zend/zend_objects.c
    ${PHP_SRC}/Zend/zend_observer.c
    ${PHP_SRC}/Zend/zend_opcode.c
    ${PHP_SRC}/Zend/zend_operators.c
    ${PHP_SRC}/Zend/zend_ptr_stack.c
    ${PHP_SRC}/Zend/zend_signal.c
    ${PHP_SRC}/Zend/zend_smart_str.c
    ${PHP_SRC}/Zend/zend_sort.c
    ${PHP_SRC}/Zend/zend_stack.c
    ${PHP_SRC}/Zend/zend_stream.c
    ${PHP_SRC}/Zend/zend_string.c
    ${PHP_SRC}/Zend/zend_strtod.c
    ${PHP_SRC}/Zend/zend_system_id.c
    ${PHP_SRC}/Zend/zend_variables.c
    ${PHP_SRC}/Zend/zend_virtual_cwd.c
    ${PHP_SRC}/Zend/zend_vm_opcodes.c
    ${PHP_SRC}/Zend/zend_weakrefs.c
    # --- our own sources (not from the tarball) ---
    ${PHP_VER_DIR}/internal_functions.c
    "compat/syslog.c"
    "compat/posix_stubs.c"
    # ${PHP_VER_DIR}/compat/date_stub.c OR the real ext/date is added by
    # extensions.cmake, depending on PHP_EXT_DATE.
)

set(PHP_INCLUDE_DIRS
    "${PHP_VER_DIR}"
    "${PHP_VER_DIR}/compat"
    "compat"
    "${PHP_SRC}"
    "${PHP_SRC}/main"
    "${PHP_SRC}/Zend"
    "${PHP_SRC}/TSRM"
    "${PHP_SRC}/sapi/embed"
)

set(PHP_PRIV_INCLUDE_DIRS
    "${PHP_SRC}/main/streams"
    "${PHP_SRC}/ext/hash"
    "${PHP_SRC}/ext/hash/sha3/generic64lc"
    "${PHP_SRC}/ext/hash/xxhash"
    "${PHP_SRC}/ext/json"
    "${PHP_SRC}/ext/pcre"
    "${PHP_SRC}/ext/pcre/pcre2lib"
    "${PHP_SRC}/ext/random"
    "${PHP_SRC}/ext/reflection"
    "${PHP_SRC}/ext/spl"
    "${PHP_SRC}/ext/standard"
)

