/*
 * Normally generated by configure. Provided by hand: just point at our
 * php_config.h, which sits in the same include directory.
 */
#ifndef ZEND_CONFIG_H_ESP32
#define ZEND_CONFIG_H_ESP32
#include "php_config.h"
#endif
