/*
 * Normally generated by configure; written by hand here. The values are mostly
 * cosmetic (phpinfo output, INI search paths) -- there's no Unix filesystem and
 * no shared extensions. Storage is the SD card, mounted at /sdcard.
 */
#define CONFIGURE_COMMAND       "(hand-written CMake build, no configure)"
#define PHP_ODBC_CFLAGS         ""
#define PHP_ODBC_LFLAGS         ""
#define PHP_ODBC_LIBS           ""
#define PHP_ODBC_TYPE           ""
#define PHP_OCI8_DIR            ""
#define PHP_OCI8_ORACLE_VERSION ""
#define PHP_PROG_SENDMAIL       ""
#define PEAR_INSTALLDIR         ""
#define PHP_INCLUDE_PATH        ".:"
#define PHP_EXTENSION_DIR       "/sdcard"
#define PHP_PREFIX              "/sdcard"
#define PHP_BINDIR              "/sdcard"
#define PHP_SBINDIR             "/sdcard"
#define PHP_MANDIR              "/sdcard"
#define PHP_LIBDIR              "/sdcard"
#define PHP_DATADIR             "/sdcard"
#define PHP_SYSCONFDIR          "/sdcard"
#define PHP_LOCALSTATEDIR       "/sdcard"
#define PHP_CONFIG_FILE_PATH    "/sdcard"
#define PHP_CONFIG_FILE_SCAN_DIR ""
#define PHP_SHLIB_SUFFIX        "so"
#define PHP_SHLIB_EXT_PREFIX    ""
