<?php
/**
 * page.php -- the control page template. Receives $color (the current LED state {h,s,v,on,effect}) and
 * $init (its JSON) from index.php. The swatch (always visible) and the slider positions are
 * server-rendered from $color; app.js then hydrates and keeps everything live over the WebSocket.
 */
?>
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ESP32-S3 RGB</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body { margin: 0; font-family: system-ui, sans-serif; background: #14161a; color: #e8eaed;
         min-height: 100vh; display: flex; align-items: center; justify-content: center; }
  .card { width: min(92vw, 26rem); background: #1d2026; border: 1px solid #2c303a;
          border-radius: 1rem; padding: 1.5rem 1.5rem 1.75rem; box-shadow: 0 8px 30px #0006; }
  h1 { font-size: 1.15rem; margin: 0 0 1.25rem; font-weight: 600; }
  h1 small { color: #8b93a1; font-weight: 400; }
  .swatch { height: 7rem; border-radius: .75rem; margin-bottom: 1.1rem; border: 1px solid #2c303a;
            transition: background .12s linear; }
  .tabs { display: flex; gap: .4rem; margin: 0 0 1.15rem; }
  .tab { flex: 1; padding: .5rem; border-radius: .55rem; border: 1px solid #2c303a; background: #191c22;
         color: #aab2c0; font-size: .85rem; cursor: pointer; }
  .tab.active { background: #262a33; color: #e8eaed; border-color: #3a4150; }
  .panel { display: none; }
  .panel.active { display: block; }
  label { display: flex; justify-content: space-between; font-size: .82rem; color: #aab2c0;
          margin: 0 0 .35rem; }
  label b { color: #e8eaed; font-variant-numeric: tabular-nums; font-weight: 600; }
  input[type=range] { width: 100%; margin: 0 0 1.1rem; accent-color: #6ea8fe; }
  .row { display: flex; gap: .6rem; align-items: center; margin-top: .25rem; }
  button.wide { flex: 1; padding: .7rem; border-radius: .6rem; border: 1px solid #2c303a;
                background: #262a33; color: #e8eaed; font-size: .9rem; cursor: pointer; }
  button.wide.on { background: #244; border-color: #2f6f6f; }
  .note { margin: 0 0 .8rem; font-size: .76rem; color: #8b93a1; }
  .fx { display: grid; grid-template-columns: 1fr 1fr; gap: .6rem; }
  .fx-btn { padding: .8rem .6rem; border-radius: .6rem; border: 1px solid #2c303a; background: #262a33;
            color: #e8eaed; font-size: .9rem; cursor: pointer; text-align: left; }
  .fx-btn.active { background: #2c3550; border-color: #6ea8fe; color: #fff; }
  .fx-btn small { display: block; color: #8b93a1; font-size: .72rem; margin-top: .15rem; }
  .fx-btn.active small { color: #c7d2e6; }
  .hint { margin: 1.1rem 0 0; font-size: .74rem; color: #6b7280; text-align: center; }
  .hint b { color: #9aa3b2; font-weight: 600; }
</style>
</head>
<body>
<div class="card">
  <h1>ESP32-S3 RGB <small>&mdash; live over WebSocket</small></h1>
  <div class="swatch" id="swatch"></div>

  <div class="tabs">
    <button class="tab active" data-tab="colour">Colour</button>
    <button class="tab" data-tab="effects">Effects</button>
    <button class="tab" data-tab="js">JS FX</button>
  </div>

  <div class="panel active" id="tab-colour">
    <label>Hue <b><span id="hL"><?= $color['h'] ?></span>&deg;</b></label>
    <input type="range" id="h" min="0" max="359" value="<?= $color['h'] ?>">

    <label>Saturation <b><span id="sL"><?= $color['s'] ?></span></b></label>
    <input type="range" id="s" min="0" max="255" value="<?= $color['s'] ?>">

    <label>Brightness <b><span id="vL"><?= $color['v'] ?></span></b></label>
    <input type="range" id="v" min="0" max="255" value="<?= $color['v'] ?>">

    <div class="row">
      <button id="toggle" class="wide <?= $color['on'] ? 'on' : '' ?>"><?= $color['on'] ? 'LED is ON' : 'LED is OFF' ?></button>
    </div>
  </div>

  <div class="panel" id="tab-effects">
    <p class="note">Run on the board (keep going with no browser open):</p>
    <div class="fx">
      <button class="fx-btn" data-fx="none">Off / manual<small>stop the effect</small></button>
      <button class="fx-btn" data-fx="disco">Disco<small>random colours</small></button>
      <button class="fx-btn" data-fx="rainbow">Rainbow<small>sweep the hue</small></button>
      <button class="fx-btn" data-fx="pulse">Pulse<small>breathe brightness</small></button>
      <button class="fx-btn" data-fx="strobe">Strobe<small>hard on/off</small></button>
    </div>
  </div>

  <div class="panel" id="tab-js">
    <p class="note">Run in your browser (this tab builds them in JS and streams the colours):</p>
    <div class="fx" id="fx-js"><!-- buttons generated by app.js --></div>
  </div>

  <p class="hint" id="status"><b>connecting&hellip;</b></p>
</div>

<script>window.__S = <?= $init ?>;</script>
<script src="/app.js"></script>
</body>
</html>
