#!/usr/bin/env bash
# Download the oniguruma regex library into components/php/oniguruma/. Only needed
# when the optional mbstring mb_ereg*/mb_split support is enabled
# (-DPHP_EXT_MBSTRING_ONIG=ON). PHP does not bundle oniguruma; mbstring normally
# links a system libonig. Kept out of git (see .gitignore). Idempotent.
set -euo pipefail

ONIG_VERSION="6.9.9"
TARBALL="onig-${ONIG_VERSION}.tar.gz"
SHA256="60162bd3b9fc6f4886d4c7a07925ffd374167732f55dce8c491bfd9cd818a6cf"
URL="https://github.com/kkos/oniguruma/releases/download/v${ONIG_VERSION}/${TARBALL}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="${REPO_ROOT}/components/php/oniguruma"

if [ -f "${DEST}/src/oniguruma.h" ]; then
    echo "Already present: ${DEST}"
    exit 0
fi

TMP="$(mktemp -d)"
trap 'rm -rf "${TMP}"' EXIT

echo "Downloading ${TARBALL}..."
curl -fsSL -o "${TMP}/${TARBALL}" "${URL}"

echo "Checking sha256..."
echo "${SHA256}  ${TMP}/${TARBALL}" | sha256sum -c -

echo "Extracting into ${DEST}..."
mkdir -p "${DEST}"
tar xzf "${TMP}/${TARBALL}" -C "${DEST}" --strip-components=1

# oniguruma's build normally runs ./configure to generate src/config.h. We don't,
# so drop in a hand-written one for the ESP32-P4 (riscv32 ILP32, newlib). regenc.h
# includes it unconditionally; only these few macros are actually used by the sources.
cat > "${DEST}/src/config.h" <<'EOF'
/* Hand-written oniguruma config.h for the ESP32-P4 (riscv32 ILP32, newlib).
 * Normally generated by ./configure; only the macros the sources touch are set. */
#ifndef ONIG_ESP32_CONFIG_H
#define ONIG_ESP32_CONFIG_H

#define HAVE_STDIO_H     1
#define HAVE_STDLIB_H    1
#define HAVE_STRING_H    1
#define HAVE_STRINGS_H   1
#define HAVE_INTTYPES_H  1
#define HAVE_STDINT_H    1
#define HAVE_SYS_TYPES_H 1
#define HAVE_SYS_STAT_H  1
#define HAVE_UNISTD_H    1
#define STDC_HEADERS     1

/* 32-bit RISC-V, ILP32 */
#define SIZEOF_INT       4
#define SIZEOF_LONG      4
#define SIZEOF_LONG_LONG 8
#define SIZEOF_VOIDP     4

#define PACKAGE          "onig"
#define PACKAGE_VERSION  "6.9.9"
#define VERSION          "6.9.9"

#endif
EOF

echo "Done: ${DEST}"
