# Dynamic partition table.
#
# The board ships a committed partitions.csv as the spec for the fixed partitions (nvs, phy_init,
# factory). The `storage` partition -- the read-only FAT image that holds the PHP source for an
# "embedded" build -- is generated here instead of being fixed:
#
#   - embedded project (PHP_EMBED_SRC set): a `storage` partition sized just above the source
#     (cluster-accurate occupancy + FAT overhead + the configurable [storage] reserve_kb).
#   - microSD project: no `storage` partition at all. main.c looks it up by name and falls back to
#     the card when it is absent, so that flash stays free.
#
# The generated CSV is written into the project's build/ (never committed) and selected via a
# sdkconfig fragment appended to SDKCONFIG_DEFAULTS -- layered last, so it wins over the board's
# committed CONFIG_PARTITION_TABLE_CUSTOM_FILENAME. Must be included before project().
#
# Inputs: BOARD_DIR, REPO_ROOT (resolve-board.cmake); PHP_EMBED_SRC, PHP_STORAGE_RESERVE_KB,
# PHP_PARTITIONS_CSV (-D from flash-tool); it appends to SDKCONFIG_DEFAULTS in the caller's scope.

# The fixed-partition spec. A project can override the board's committed table by passing
# PHP_PARTITIONS_CSV (flash-tool sets it when a partitions.csv sits next to the project config);
# the generated storage/phpstore partitions below are appended either way.
if(DEFINED PHP_PARTITIONS_CSV AND NOT PHP_PARTITIONS_CSV STREQUAL "")
    set(_board_csv "${PHP_PARTITIONS_CSV}")
    if(NOT IS_ABSOLUTE "${_board_csv}")
        set(_board_csv "${REPO_ROOT}/${_board_csv}")
    endif()
    message(STATUS "php-esp32: partition table base <- project override (${_board_csv})")
else()
    set(_board_csv "${BOARD_DIR}/partitions.csv")
endif()
if(NOT EXISTS "${_board_csv}")
    message(FATAL_ERROR "partition table: ${_board_csv} not found")
endif()

# Keep the board's fixed partitions (everything that isn't the storage line or a comment).
file(STRINGS "${_board_csv}" _board_lines)
set(_csv "# Generated by cmake/gen-partitions.cmake -- do not edit; regenerated each build.\n")
string(APPEND _csv "# Name,     Type, SubType,  Offset,   Size\n")
foreach(_line ${_board_lines})
    string(STRIP "${_line}" _stripped)
    if(_stripped STREQUAL "" OR _stripped MATCHES "^#")
        continue()
    endif()
    if(_stripped MATCHES "^storage[ \t,]")
        continue()   # regenerated (or dropped) below
    endif()
    string(APPEND _csv "${_line}\n")
endforeach()

if(DEFINED PHP_EMBED_SRC AND NOT PHP_EMBED_SRC STREQUAL "")
    set(_src "${PHP_EMBED_SRC}")
    if(NOT IS_ABSOLUTE "${_src}")
        set(_src "${REPO_ROOT}/${_src}")
    endif()

    # Cluster-accurate occupancy: fatfsgen uses 4 KB sectors/clusters, so each file rounds up. This
    # counts many small files (a vendor/ tree) correctly instead of undercounting by raw byte sum.
    set(_occ 0)
    file(GLOB_RECURSE _emb_files LIST_DIRECTORIES false CONFIGURE_DEPENDS "${_src}/*")
    foreach(_f ${_emb_files})
        file(SIZE "${_f}" _fs)
        math(EXPR _cl "((${_fs} + 4095) / 4096) * 4096")
        math(EXPR _occ "${_occ} + ${_cl}")
    endforeach()

    if(NOT DEFINED PHP_STORAGE_RESERVE_KB OR "${PHP_STORAGE_RESERVE_KB}" STREQUAL "")
        set(PHP_STORAGE_RESERVE_KB 0)
    endif()
    math(EXPR _reserve_b "${PHP_STORAGE_RESERVE_KB} * 1024")

    # + 64 KB FAT overhead (boot sector, FAT tables, root directory) + the configured reserve;
    # aligned up to 64 KB, floored at 128 KB (fatfsgen needs a valid minimum).
    math(EXPR _size "${_occ} + 65536 + ${_reserve_b}")
    math(EXPR _size "((${_size} + 65535) / 65536) * 65536")
    if(_size LESS 131072)
        set(_size 131072)
    endif()
    math(EXPR _size_k "${_size} / 1024")

    string(APPEND _csv "storage,    data, fat,      ,         ${_size_k}K\n")
    message(STATUS "php-esp32: embedded 'storage' partition = ${_size_k}K "
                   "(source ~${_occ} B occupancy + 64K FAT + ${PHP_STORAGE_RESERVE_KB}K reserve)")
else()
    message(STATUS "php-esp32: microSD project -- no 'storage' partition (source runs from the card)")
endif()

# Reboot-persistent key-value store (the `store` extension). When the project sets [store] size_kb
# (flash-tool passes -DPHP_STORE_KB), add a dedicated NVS partition of that size, aligned to 4 KB
# with a 16 KB floor. Absent/0 -> no partition, and store_available() is false. Independent of the
# embedded/microSD choice above.
if(DEFINED PHP_STORE_KB AND NOT "${PHP_STORE_KB}" STREQUAL "" AND PHP_STORE_KB GREATER 0)
    math(EXPR _store_b "${PHP_STORE_KB} * 1024")
    math(EXPR _store_b "((${_store_b} + 4095) / 4096) * 4096")   # NVS partitions align to 4 KB
    if(_store_b LESS 16384)
        set(_store_b 16384)                                       # NVS needs a few pages to be useful
    endif()
    math(EXPR _store_k "${_store_b} / 1024")
    string(APPEND _csv "phpstore,   data, nvs,      ,         ${_store_k}K\n")
    message(STATUS "php-esp32: persistent 'phpstore' NVS partition = ${_store_k}K")
endif()

# Write the generated CSV into the project's build/ (the parent of the CMake binary dir, which is
# <project>/build/compiled). Never committed.
get_filename_component(_build_root "${CMAKE_BINARY_DIR}" DIRECTORY)
set(_gen_csv "${_build_root}/partitions.gen.csv")
file(WRITE "${_gen_csv}" "${_csv}")

# Select it: an absolute path in the partition-table filename, layered last over the board default.
set(_part_frag "${CMAKE_BINARY_DIR}/partitions.sdkconfig.defaults")
file(WRITE "${_part_frag}" "CONFIG_PARTITION_TABLE_CUSTOM_FILENAME=\"${_gen_csv}\"\n")
list(APPEND SDKCONFIG_DEFAULTS "${_part_frag}")
message(STATUS "php-esp32: partition table -> ${_gen_csv}")
